### ISSUE TITLE
Profile Content Page

### ISSUE THREAD

**Issue by R-Schreyer** [neuefische/hh-java-24-1-team-4#13]
**As a User**
**I need** need to see my profile data
**to be able to** check if they are up to date

## Description
The page shows my profile data.

## Acceptance Criteria
- [ ]  the user information is displayd:
- [ ] comtains: firstname, lastname, email, password as stars, 

## Tasks
- [ ] create a p tag for every named user key value pair
