### ISSUE TITLE
Workout Page

### ISSUE THREAD

**Issue by R-Schreyer** [neuefische/hh-java-24-1-team-4#14]
**As a User** 
**I need** see all workout cards on the page.
**to be able to** get a overview of my Workouts cards.

## Description
When I visit the workout page, I should see a list of all available workout cards.
?? Each workout card should display the workout's name, intensity, description, duration, burnedCaloriesPerHourAndUserWeight 
Clicking on a workout card should take me to a detailed view of that workout.

## Acceptance Criteria
- [ ] All Workouts are displayed with some minimal informations.

## Tasks
- [ ] Create a component for displaying workout cards.
- [ ] Fetch workout data from WorkoutRepo
- [ ] map over the list and display the WorkoutCard for each Workout
