### ISSUE TITLE
Add UserData Form

### ISSUE THREAD

**Issue by luederb** [neuefische/hh-java-24-1-team-4#2]
**As a User** 
**I need** to add my current weight and hight
**to be able to** to get my current BMI

## Description
Implement a feature that allows a user to input their weight and hight and let it be displayed in a user Card

## Acceptance Criteria
- [x] On the 'my Data' page, two input fields for 'name', 'weight' and 'height' are displayed
- [x] A input change automatically updates the user data information fields
- [x] the name, weight and height of the user are displayed in a `userCard` - Card with the lines 
  - [x] `name`
  - [x] `weight` and
  - [x] `height` 

## Tasks
- [x] create a userCard section, with the fields for the user Name, their weight and hight. The default values should be empty
- [x] create a 'updateUserData' function, that takes the data from the form and updates the a 'userData' useState variable with the user.height and user.weight values
- [x] Implement a form with three input fields, where the user can input their name, weight (kg) and hight (cm).
