### ISSUE TITLE
Create basic Controller for the userData

### ISSUE THREAD

**Issue by luederb** [neuefische/hh-java-24-1-team-4#7]
**As a User**
**I need** be able to access my data from the backend
**to be able to** update and interact with my data

## Description
Create a Controller, that connects the frontend with the backend and distributes the frontend requests to the corresponding backend service functions

## Acceptance Criteria
- [ ] The Controller can handle all CRUD methods and distributes the requests / data to the corresponding Service functions.

## Tasks
- [ ] Create a GET method for the userData
- [ ] Create a POST method for the userData
- [ ] Create a PUT method for the userData
- [ ] Create a DELETE method for the userData
- [ ] Make sure that these methods can receive and sent the data from and to the frontend
