### ISSUE TITLE
Frontend Layout

### ISSUE THREAD

**Issue by R-Schreyer** [neuefische/hh-java-24-1-team-4#9]
**As a User** 
**I need** to see the content of the app.
**to be able to** interact with the app.

## Description
Layout from the app, with a header, a navbar and a main section.
The navbar contains the links to the profile, the workoutlist and the workoutplan.

## Acceptance Criteria
- [ ]  A header is displayed
- [ ]  The navbar must contains links to the 3 pages. A click on the linkss  opens the corresponding pages with the correct pathname.

## Tasks
- [ ]  Create a layoutcomponent to layout the app with the help of the react node hook.
- [ ]  In the app.tsx define the three pages with the routes hook from react.
